user:
    resource: '@QuizzBundle/Controller/UserController.php'
    type:     annotation

game:
    resource: '@QuizzBundle/Controller/GameController.php'
    type:     annotation
    prefix:   /game

response:
    resource: '@QuizzBundle/Controller/ResponseController.php'
    type:     annotation
    prefix:   /response

question:
    resource: '@QuizzBundle/Controller/QuestionController.php'
    type:     annotation
    prefix:   /question

offline_game:
    resource: '@QuizzBundle/Controller/OfflineGameController.php'
    type:     annotation
    prefix:   /offGame

stat:
    resource: '@QuizzBundle/Controller/StatController.php'
    type:     annotation
    prefix:   /stats