<?php

namespace QuizzBundle\Repository;

use Doctrine\ORM\NonUniqueResultException;
use QuizzBundle\Entity\User;

/**
 * InvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationRepository extends \Doctrine\ORM\EntityRepository
{

    public function getNbInvitationsToMe(User $user)
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->addSelect('count(a.id)')
            ->where('a.played = 0')
            ->andWhere('a.userTo = :id')
            ->setParameter('id', $user)
            ->getQuery();

        $count = $qb->execute()[0][1];
        return $count;

    }
}
