<?php

namespace QuizzBundle\Repository;

/**
 * RoundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoundRepository extends \Doctrine\ORM\EntityRepository
{
}
