<?php

namespace QuizzBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUsersByText($text){
        $qb = $this->createQueryBuilder('u');

        $qb->where('u.username like :text')
            ->setParameter('text', $text."%")
            ->setMaxResults(5);

        return $qb
            ->getQuery()
            ->getResult();
    }
}
