security:

    always_authenticate_before_granting:  true
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER: IS_AUTHENTICATED_ANONYMOUSLY
        ROLE_ADMIN: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
            anonymous: true
        main:
            pattern: ^/
            anonymous: true
            provider: fos_userbundle
            logout:
                path: /logout
                target: /success
            form_login:
                require_previous_session: false
                login_path: fail
                check_path: /login_check
                default_target_path: success
                always_use_default_target_path: true
                failure_path: fail
            json_login:
                require_previous_session: false
                check_path: /login
                username_path: username
                password_path: plainPassword

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/createUser$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/success$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fail$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/question/all, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/stats/up, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }